In [1]:
#import packles
import numpy as np  
import pickle
import pandas as pd
from matplotlib import pyplot as plt
import cv2
import os

In [2]:
#读取彩色图片，忽略alpha通道
image = cv2.imread('dataset/image/IMAGE_0000.jpg',cv2.IMREAD_GRAYSCALE)
#打印图片
print('image:',image)
print(type(image))
#打印图片维度形状
print('image.shape:',image.shape)
#显示图片
cv2.imshow('image:',image)
#防止图片关闭
cv2.waitKey(0)



image: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>
image.shape: (512, 512)


-1

In [3]:
alldata = [] # this if for store all of the image data
# this function is for read image,the input is directory name
def read_directory(directory_name):
    # this loop is for read each image in this foder,directory_name is the foder name with images.
    for filename in os.listdir(r"./"+directory_name):
        print(filename) #just for test
        #img is used to store the image data 
        img = cv2.imread(directory_name + "/" + filename,cv2.IMREAD_GRAYSCALE)
        alldata.append(img)
        #print(img)
        #print(alldata)


In [4]:
read_directory("dataset/image1")
print(type(alldata))
#alldata=np.array(alldata)
#alldata.shape

IMAGE_0000.jpg
IMAGE_0001.jpg
IMAGE_0002.jpg
IMAGE_0003.jpg
IMAGE_0004.jpg
IMAGE_0005.jpg
IMAGE_0006.jpg
IMAGE_0007.jpg
IMAGE_0008.jpg
IMAGE_0009.jpg
<class 'list'>


In [5]:
a=np.array(alldata)
print(a.shape)
print(a)

(10, 512, 512)
[[[  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  ...
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]
  [  0   0   0 ...   0   0   0]]

 [[ 35  36  37 ...  56 100 122]
  [ 28  28  29 ...  51  93 114]
  [ 14  15  15 ...  39  80 100]
  ...
  [  2   2   3 ...  30  72  93]
  [  2   3   3 ...  30  73  94]
  [  2   3   3 ...  30  74  95]]

 [[ 21  12   2 ...   0   0   0]
  [ 20  14   6 ...   0   0   0]
  [ 18  14   7 ...   0   0   0]
  ...
  [  1   1   1 ...   1   1   1]
  [  1   1   1 ...   1   1   1]
  [  2   2   2 ...   2   2   2]]

 ...

 [[  0   0   0 ...   1   1   1]
  [  0   0   0 ...   1   1   1]
  [  0   0   0 ...   1   1   1]
  ...
  [  0   0   0 ...   1   1   1]
  [  0   0   0 ...   1   1   1]
  [  0   0   0 ...   1   1   1]]

 [[101 100  96 ... 138 193 234]
  [101 100  96 ... 205 228 245]
  [102 100  96 ... 237 251 255]
  ...
  [  7   7   7 ...   7   7   7]
  [  7   7   7 ...   7   7   7]
  [  7   7   

In [8]:
np.save(file="alldata.npy", arr=a)

In [12]:
b= np.load(file="alldata.npy")
b.shape

(10, 512, 512)

In [6]:
#file = open('alldata.txt','w');

#file.write(str(alldata));

#file.close();