In [1]:
#import packles
import numpy as np  
import pickle
import pandas as pd
from matplotlib import pyplot as plt
import cv2
import os

In [14]:
#读取彩色图片，忽略alpha通道
image = cv2.imread('dataset/image/IMAGE_0000.jpg',cv2.IMREAD_GRAYSCALE)
#打印图片
print('image:',image)
print(type(image))
#打印图片维度形状
print('image.shape:',image.shape)
#显示图片
cv2.imshow('image:',image)
#防止图片关闭
cv2.waitKey(0)



image: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>
image.shape: (512, 512)


-1

In [3]:
alldata = [] # this if for store all of the image data
# this function is for read image,the input is directory name
def read_directory(directory_name):
    # this loop is for read each image in this foder,directory_name is the foder name with images.
    for filename in os.listdir(r"./"+directory_name):
        #print(filename) #just for test
        #img is used to store the image data 
        img = cv2.imread(directory_name + "/" + filename,cv2.IMREAD_GRAYSCALE)
        alldata.append(img)
        #print(img)
        #print(alldata)


In [4]:
read_directory("dataset/image1")
#print(type(alldata))
#alldata=np.array(alldata)
#alldata.shape

In [5]:
npdata=np.array(alldata)
print(npdata.shape)
#print(a)

(3000, 512, 512)


In [6]:
np.save(file="alldata.npy", arr=npdata)

In [7]:
b= np.load(file="alldata.npy")
b.shape

(3000, 512, 512)

In [16]:
print(b[0, ::])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
image3=b[3,::]
cv2.imshow('image:',image3)
#防止图片关闭
cv2.waitKey(0)

-1